DROP TABLE M_DEPARTMENT CASCADE CONSTRAINTS PURGE
/
DROP TABLE M_DRUG CASCADE CONSTRAINTS PURGE
/
DROP TABLE M_STAFF CASCADE CONSTRAINTS PURGE
/
DROP TABLE T_CASE_RECORD CASCADE CONSTRAINTS PURGE
/
DROP TABLE T_PATIENT CASCADE CONSTRAINTS PURGE
/
DROP TABLE T_PRESCRIPTION CASCADE CONSTRAINTS PURGE
/
DROP TABLE T_PRESCRIPTION_DETAIL CASCADE CONSTRAINTS PURGE
/
DROP TABLE T_REGISTER CASCADE CONSTRAINTS PURGE
/
