CREATE TABLE M_DEPARTMENT (
    DEPT_CODE VARCHAR2(7),
    DEPT_NAME VARCHAR2(50)
)
/
ALTER TABLE M_DEPARTMENT ADD CONSTRAINT PK_M_DEPARTMENT PRIMARY KEY (DEPT_CODE)
/

CREATE TABLE T_REGISTER (
    REGISTER_NO CHAR(14),
    REGISTER_DATETIME DATE,
    REGISTER_FEE NUMBER(10, 2),
    PATIENT_NO CHAR(12),
    DEPT_CODE VARCHAR2(7),
    STAFF_CODE CHAR(13)
)
/
ALTER TABLE T_REGISTER ADD CONSTRAINT PK_T_REGISTER PRIMARY KEY (REGISTER_NO)
/
COMMENT ON TABLE M_DEPARTMENT IS '部门表'
/
COMMENT ON COLUMN M_DEPARTMENT.DEPT_CODE IS '科室代码'
/
COMMENT ON COLUMN M_DEPARTMENT.DEPT_NAME IS '科室名称';
/
