CREATE TABLE M_DEPARTMENT (
    DEPT_CODE VARCHAR2(7),
    DEPT_NAME VARCHAR2(50)
)
/
ALTER TABLE M_DEPARTMENT ADD CONSTRAINT PK_M_DEPARTMENT PRIMARY KEY (DEPT_CODE)
/
COMMENT ON TABLE M_DEPARTMENT IS '部门表'
/
COMMENT ON COLUMN M_DEPARTMENT.DEPT_CODE IS '科室代码'
/
COMMENT ON COLUMN M_DEPARTMENT.DEPT_NAME IS '科室名称'
/
