CREATE TABLE M_DRUG (
    DRUG_CODE CHAR(10),
    CATEGORY VARCHAR2(8),
    DRUG_NAME VARCHAR2(20),
    TRADE_NAME VARCHAR2(10),
    DRUG_SPEC VARCHAR2(40),
    RETAIL_PRICE NUMBER(10, 2),
    WHOLE_SALE_PRICE NUMBER(10, 2),
    BUY_PRICE NUMBER(10, 2),
    DRUG_AMOUNT NUMBER(10, 2)
)
/
ALTER TABLE M_DRUG ADD CONSTRAINT PK_M_DRUG PRIMARY KEY (DRUG_CODE)
/
COMMENT ON TABLE M_DRUG IS '药品表'
/
COMMENT ON COLUMN M_DRUG.DRUG_CODE IS '药品代码'
/
COMMENT ON COLUMN M_DRUG.CATEGORY IS '药品类别'
/
COMMENT ON COLUMN M_DRUG.DRUG_NAME IS '药品名称'
/
COMMENT ON COLUMN M_DRUG.TRADE_NAME IS '名称类别'
/
COMMENT ON COLUMN M_DRUG.DRUG_SPEC IS '药品规格'
/
COMMENT ON COLUMN M_DRUG.RETAIL_PRICE IS '零售价'
/
COMMENT ON COLUMN M_DRUG.WHOLE_SALE_PRICE IS '批发价'
/
COMMENT ON COLUMN M_DRUG.BUY_PRICE IS '购入价'
/
COMMENT ON COLUMN M_DRUG.DRUG_AMOUNT IS '药品数量'
/
