CREATE TABLE M_STAFF (
    STAFF_CODE CHAR(13),
    STAFF_NAME VARCHAR2(10),
    SEX CHAR(1),
    BIRTHDAY DATE,
    ID CHAR(18),
    PHONE_NUMBER VARCHAR2(12),
    POSITION VARCHAR2(10),
    SALARY NUMBER(10, 2),
    START_WORK_DATE DATE,
    EDUCATION_LEVEL VARCHAR2(10),
    ADDRESS VARCHAR2(50),
    ZIP_CODE CHAR(6),
    REMARK VARCHAR2(100),
    DEPT_CODE VARCHAR2(7)
)
/
ALTER TABLE M_STAFF ADD CONSTRAINT PK_M_STAFF PRIMARY KEY (STAFF_CODE)
/
ALTER TABLE M_STAFF ADD CONSTRAINT FK_M_STAFF_M_DEPT FOREIGN KEY (DEPT_CODE) REFERENCES M_DEPARTMENT(DEPT_CODE)
/
COMMENT ON TABLE M_STAFF IS '员工表'
/