CREATE TABLE M_STAFF (
    STAFF_CODE CHAR(13),
    STAFF_NAME VARCHAR2(10),
    SEX CHAR(1),
    BIRTHDAY DATE,
    ID CHAR(18),
    PASSWORD VARCHAR(12),
    PHONE_NUMBER VARCHAR2(12),
    POSITION VARCHAR2(10),
    SALARY NUMBER(10, 2),
    START_WORK_DATE DATE,
    EDUCATION_LEVEL VARCHAR2(10),
    ADDRESS VARCHAR2(50),
    ZIP_CODE CHAR(6),
    REMARK VARCHAR2(100),
    DEPT_CODE VARCHAR2(7)
)
/
ALTER TABLE M_STAFF ADD CONSTRAINT PK_M_STAFF PRIMARY KEY (STAFF_CODE)
/
ALTER TABLE M_STAFF ADD CONSTRAINT FK_M_STAFF_M_DEPT FOREIGN KEY (DEPT_CODE) REFERENCES M_DEPARTMENT(DEPT_CODE)
/
COMMENT ON TABLE M_STAFF IS '员工表'
/
COMMENT ON COLUMN M_STAFF.STAFF_CODE IS '员工代码'
/
COMMENT ON COLUMN M_STAFF.STAFF_NAME IS '员工姓名'
/
COMMENT ON COLUMN M_STAFF.SEX IS '性别'
/
COMMENT ON COLUMN M_STAFF.BIRTHDAY IS '出生日期'
/
COMMENT ON COLUMN M_STAFF.ID IS '身份证号'
/
COMMENT ON COLUMN M_STAFF.PASSWORD IS '密码'
/
COMMENT ON COLUMN M_STAFF.PHONE_NUMBER IS '电话号码'
/
COMMENT ON COLUMN M_STAFF.POSITION IS '职位'
/
COMMENT ON COLUMN M_STAFF.SALARY IS '工资'
/
COMMENT ON COLUMN M_STAFF.START_WORK_DATE IS '参加工作日期'
/
COMMENT ON COLUMN M_STAFF.EDUCATION_LEVEL IS '学历'
/
COMMENT ON COLUMN M_STAFF.ADDRESS IS '住址'
/
COMMENT ON COLUMN M_STAFF.ZIP_CODE IS '邮政编码'
/
COMMENT ON COLUMN M_STAFF.REMARK IS '备注'
/
COMMENT ON COLUMN M_STAFF.DEPT_CODE IS '科室代码'
/
