CREATE TABLE T_CASE_RECORD (
    CASE_REC_NO CHAR(14),
    CONSULTATION_DATE DATE,
    MAIN_SYMPTOM VARCHAR2(100),
    STAFF_CODE CHAR(13),
    PATIENT_NO CHAR(12)
)
/
ALTER TABLE T_CASE_RECORD ADD CONSTRAINT PK_T_CASE_RECORD PRIMARY KEY (CASE_REC_NO)
/
ALTER TABLE T_CASE_RECORD ADD CONSTRAINT FK_T_CASE_RECORD_M_STAFF FOREIGN KEY (STAFF_CODE) REFERENCES M_STAFF(STAFF_CODE)
/
ALTER TABLE T_CASE_RECORD ADD CONSTRAINT FK_T_CASE_RECORD_M_PATIENT FOREIGN KEY (PATIENT_NO) REFERENCES T_PATIENT(PATIENT_NO)
/
COMMENT ON TABLE T_CASE_RECORD IS '病历表'
/
COMMENT ON COLUMN T_CASE_RECORD.CASE_REC_NO IS '病历编号'
/
COMMENT ON COLUMN T_CASE_RECORD.CONSULTATION_DATE IS '就诊日期'
/
COMMENT ON COLUMN T_CASE_RECORD.MAIN_SYMPTOM IS '主要症状'
/
COMMENT ON COLUMN T_CASE_RECORD.STAFF_CODE IS '接诊医生'
/
COMMENT ON COLUMN T_CASE_RECORD.PATIENT_NO IS '就诊病人'
/
