CREATE TABLE T_PATIENT (
    PATIENT_NO CHAR(12),
    PATIENT_NAME VARCHAR2(10),
    SEX CHAR(1),
    BIRTHDAY DATE,
    ID CHAR(18),
    PHONE_NUMBER VARCHAR2(12),
    ADDRESS VARCHAR2(50),
    ZIP_CODE CHAR(6),
    DRUG_ALLERGY_HISTORY VARCHAR2(100),
    JOB_INFO VARCHAR2(10),
    CREATE_CODE CHAR(13),
    CREATE_DATE DATE,
    UPDATE_CODE CHAR(13),
    UPDATE_DATE DATE
)
/
ALTER TABLE T_PATIENT ADD CONSTRAINT PK_T_PATIENT PRIMARY KEY (PATIENT_NO)
/
COMMENT ON TABLE T_PATIENT IS '病人表'
/
COMMENT ON COLUMN T_PATIENT.PATIENT_NO IS '病人编号'
/
COMMENT ON COLUMN T_PATIENT.PATIENT_NAME IS '姓名'
/
COMMENT ON COLUMN T_PATIENT.SEX IS '性别'
/
COMMENT ON COLUMN T_PATIENT.BIRTHDAY IS '出生日期'
/
COMMENT ON COLUMN T_PATIENT.ID IS '身份证号'
/
COMMENT ON COLUMN T_PATIENT.PHONE_NUMBER IS '电话号码'
/
COMMENT ON COLUMN T_PATIENT.ADDRESS IS '住址'
/
COMMENT ON COLUMN T_PATIENT.ZIP_CODE IS '邮政编码'
/
COMMENT ON COLUMN T_PATIENT.DRUG_ALLERGY_HISTORY IS '过敏药物'
/
COMMENT ON COLUMN T_PATIENT.JOB_INFO IS '职业'
/
COMMENT ON COLUMN T_PATIENT.CREATE_CODE IS '创建者编码'
/
COMMENT ON COLUMN T_PATIENT.CREATE_DATE IS '创建日时'
/
COMMENT ON COLUMN T_PATIENT.UPDATE_CODE IS '更新者编码'
/
COMMENT ON COLUMN T_PATIENT.UPDATE_DATE IS '更新日时'
/
