CREATE TABLE T_PRESCRIPTION_DETAIL (
    PRESCRIPTION_NO CHAR(14),
    SEQ_NO NUMBER(3, 0),
    DRUG_CODE CHAR(10),
    QUANTITY NUMBER(3, 0),
    CREATE_CODE CHAR(13),
    CREATE_DATE DATE,
    UPDATE_CODE CHAR(13),
    UPDATE_DATE DATE
)
/
ALTER TABLE T_PRESCRIPTION_DETAIL ADD CONSTRAINT PK_T_PRESCRIPTION_DETAIL PRIMARY KEY (PRESCRIPTION_NO, SEQ_NO)
/
ALTER TABLE T_PRESCRIPTION_DETAIL ADD CONSTRAINT FK_T_PRESCRIPTION_DETAIL_T_CASE_RECORD FOREIGN KEY (PRESCRIPTION_NO) REFERENCES T_PRESCRIPTION(PRESCRIPTION_NO)
/
ALTER TABLE T_PRESCRIPTION_DETAIL ADD CONSTRAINT FK_T_PRESCRIPTION_DETAIL_M_DRUG FOREIGN KEY (DRUG_CODE) REFERENCES M_DRUG(DRUG_CODE)
/
COMMENT ON TABLE T_PRESCRIPTION_DETAIL IS '处方明细表'
/
COMMENT ON COLUMN T_PRESCRIPTION_DETAIL.PRESCRIPTION_NO IS '处方编号'
/
COMMENT ON COLUMN T_PRESCRIPTION_DETAIL.SEQ_NO IS '处方子编号'
/
COMMENT ON COLUMN T_PRESCRIPTION_DETAIL.DRUG_CODE IS '药品代码'
/
COMMENT ON COLUMN T_PRESCRIPTION_DETAIL.QUANTITY IS '药品数量'
/
COMMENT ON COLUMN T_PRESCRIPTION_DETAIL.CREATE_CODE IS '创建者编码'
/
COMMENT ON COLUMN T_PRESCRIPTION_DETAIL.CREATE_DATE IS '创建日时'
/
COMMENT ON COLUMN T_PRESCRIPTION_DETAIL.UPDATE_CODE IS '更新者编码'
/
COMMENT ON COLUMN T_PRESCRIPTION_DETAIL.UPDATE_DATE IS '更新日时'
/
