CREATE TABLE T_REGISTER (
    REGISTER_NO CHAR(14),
    REGISTER_DATETIME DATE,
    REGISTER_FEE NUMBER(10, 2),
    PATIENT_NO CHAR(12),
    DEPT_CODE VARCHAR2(7),
    STAFF_CODE CHAR(13)
)
/

ALTER TABLE T_REGISTER ADD CONSTRAINT PK_T_REGISTER PRIMARY KEY (REGISTER_NO)
/

ALTER TABLE T_REGISTER ADD CONSTRAINT FK_T_REGISTER_T_PATIENT FOREIGN KEY (PATIENT_NO) REFERENCES T_PATIENT(PATIENT_NO)
/
ALTER TABLE T_REGISTER ADD CONSTRAINT FK_T_REGISTER_M_DEPT FOREIGN KEY (DEPT_CODE) REFERENCES M_DEPARTMENT(DEPT_CODE)
/
ALTER TABLE T_REGISTER ADD CONSTRAINT FK_T_REGISTER_M_STAFF FOREIGN KEY (STAFF_CODE) REFERENCES M_STAFF(STAFF_CODE)
/

COMMENT ON TABLE T_REGISTER IS '挂号表'
/
COMMENT ON COLUMN T_REGISTER.REGISTER_NO IS '挂号单编号'
/
COMMENT ON COLUMN T_REGISTER.REGISTER_DATETIME IS '挂号时间'
/
COMMENT ON COLUMN T_REGISTER.REGISTER_FEE IS '挂号费'
/
COMMENT ON COLUMN T_REGISTER.PATIENT_NO IS '病人编号'
/
COMMENT ON COLUMN T_REGISTER.DEPT_CODE IS '科室代码'
/
COMMENT ON COLUMN T_REGISTER.STAFF_CODE IS '员工代码'
/
